config/routes.rb
Rails.application.routes.draw do
  resources :users, :only => [:new, :create]
  resources :products
  resources :volume_costs, only: [:new, :create, :edit, :update]
  
  resources :oils do
    resources :benefits
  end

  resources :categories do 
    resources :products, only: [:new, :create, :index]
    resources :volume_costs
  end

  get '/products/volume_costs/new' => 'volume_costs#new'

  root 'static_pages#home'
  get '/contact' => 'static_pages#contact'

  get    '/signup' => 'users#new'
  post   '/users' => 'users#create'
  get    '/login' => 'sessions#new'
  post   '/sessions' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'
  

end

app/models/benefit.rb
class Benefit < ActiveRecord::Base
  # has_many :oil_benefits
  # has_many :oils, through: :oil_benefits
  belongs_to :oil

  # validates :description, presence: true
end

app/controllers/benefits_controller.rb
class BenefitsController < ApplicationController
  before_action :set_oil
  before_action :set_benefit, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show, :index]

  def new
    @benefit = Benefit.new
  end

  def create
    @benefit = @oil.benefits.build(benefit_params)

    if @benefit.save
      respond_to do |f|
        f.html { redirect_to oil_path(@oil) }
        f.json { render :json => @benefit }
      end
    else
      render "oils/show"
    end
  end

  def index
    @benefits = @oil.benefits
  end

  def show
  end

  def edit
  end

  def update
    if @benefit.update(benefit_params)
      redirect_to benefit_path(@benefit)
    else
      redirect_to edit_benefit_path(@benefit)
    end
  end

  def destroy
    @benefit.delete

    redirect_to benefits_path
  end

  private

  def benefit_params
    params.require(:benefit).permit(:description)
  end

  def set_benefit
    @benefit = Benefit.find(params[:id])
  end

  def set_oil
    @oil = Oil.find(params[:oil_id])
  end

end

app/views/benefits/_benefits.html.erb
<ul>
  <% @oil_benefits.each do |benefit| %>
    <li><%= benefit.description %></li>
  <% end %>
</ul>

app/views/benefits/_form.html.erb
<%= form_for(@benefit) do |f| %>

  <% if @benefit.errors.any? %>
    <div class="alert alert-danger">
      <h2>
        <%= pluralize(@benefit.errors.count, "error") %>
        prohibited this benefit from being saved:
      </h2>
   
      <ul>
      <% @benefit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <br>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/benefits/edit.html.erb
<h1>Edit <%= @benefit.description %></h1>

<%= render 'form' %>

app/views/benefits/index.html.erb
<h1>Benefits</h1>

<div class="row">
  <ul>
    <% @benefits.each do |benefit| %>
      <li>
        <div class="col">
          <%= benefit.description %>
        </div>
        <div class="col">
          <%= link_to "Edit", edit_oil_benefit_path(params[:oil_id], benefit), class: "btn btn-secondary" %>
          <%= link_to "Delete", oil_benefit_path(@oil, benefit) , method: :delete, class: "btn btn-secondary", data: { confirm: "Are You Sure?" } %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/benefits/new.html.erb
<h1>New Benefit</h1>

<%= render 'form' %>

app/views/benefits/show.html.erb
<li><%= @benefit.description %></li>