config/routes.rb
Rails.application.routes.draw do
  resources :users, :only => [:new, :create]
  resources :products
  resources :volume_costs, only: [:new, :create, :edit, :update]
  
  resources :oils do
    resources :benefits
  end

  resources :categories do 
    resources :products, only: [:new, :create, :index]
    resources :volume_costs
  end

  get '/products/volume_costs/new' => 'volume_costs#new'

  root 'static_pages#home'
  get '/contact' => 'static_pages#contact'

  get    '/signup' => 'users#new'
  post   '/users' => 'users#create'
  get    '/login' => 'sessions#new'
  post   '/sessions' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  has_many :product_oils
  has_many :oils, through: :product_oils

  has_many :product_volume_costs
  has_many :volume_costs, through: :product_volume_costs

  validates :name, uniqueness: true
  validates :name, :description, :category_id, presence: true
  validates :oil_ids, :presence => {:message => "must select at least one Oil" }

  before_save :naming_convention

  scope :sort_alpha, -> { order(:name) }

  def volumes_with_data
    volume_costs.where('volume > ? AND cost > ?', 0, 0).order(:volume)
  end

  def naming_convention
    self.name = self.name.capitalize
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show, :index]

  def new
    @product = Product.new(category_id: params[:category_id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @product }
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      redirect_to edit_product_path(@product)
    end
  end

  def index
    if params[:category_id]
      @category = Category.find(params[:category_id])
      @products = @category.products.sort_alpha
    else
      @products = Product.sort_alpha
    end
    
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @products }
    end
  end

  def destroy
    @product.destroy

    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :category_id, :oil_ids => [], :volume_cost_ids => [])
  end

  def set_product
    @product = Product.find(params[:id])
  end

end

app/helpers/products_helper.rb
module ProductsHelper

  def next_product_link(action, product_id)
    if action === "show"
      link_to "Next Product", "#", class: "next-product", data: { id: product_id, limit: product_count }
    end
  end

  def product_count
    return Product.all.size
  end


# <a href="#" class="next-product" data-id=params["id"]>Next Product</a>
end

app/views/products/_form.html.erb
  <%= form_for(@product) do |f| %>

    <% if @product.errors.any? %>
      <div class="alert alert-danger">
        <h2>
          <%= pluralize(@product.errors.count, "error") %>
          prohibited this product from being saved:
        </h2>
     
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
      <label class="col-1 col-form-label"><%= f.label :name %></label>
      <div class="col-8">
      <%= f.text_field :name %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-1 col-form-label"><%= f.label :description %></label>
      <div class="col-8">
      <%= f.text_area :description %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-1 col-form-label"><%= f.label "Category" %></label>
      <div class="col-8">
        <%= f.collection_select(:category_id, Category.all, :id, :name, {:selected => @product.category_id, :prompt => 'Please select a category'}) %>
      </div>
    </div>

    <div class="form-check row">
      <label class="col-1 col-form-label"><%= f.label "Oils" %></label>
      <div class="container-fluid oils">
        <%= f.collection_check_boxes(:oil_ids, Oil.all, :id, :name) do |b| %>
          <div class="d-inline-block col-md-3">
            <%= b.check_box :class => "label-checkbox" %>
            <%= b.label %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="form-check row">
      <label class="col-1 col-form-label">
        <%= f.label "Size/Cost" %>
      </label>

      <div class="container-fluid volume_costs vol_costs"></div>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

  <% end %>

app/views/products/_product_details.html.erb
<div class="container-fluid">
  <div class="rounded card">
    <div class="card-header">
      <h4><%= link_to product.name, product_path(product), id: "productName" %></h4>
      <%= next_product_link(params["action"], product.id) %>
    </div>
    <div class="card-block">
      <h5 class="card-title">Description</h5>
      <p class="card-text" id="productDescription"><%= product.description %></p>
      <h5 class="card-title">Available Scents</h5>
      <p class="card-text">
        <ul id="productOils">
          <% product.oils.each do |oil| %>
            <li><%= oil.name %></li>
          <% end %>
        </ul>
      </p>
      <h5 class="card-title">Volume and Cost</h5>
      <p class="card-text">
        <ul id="productVolumeCost">
          <% product.volumes_with_data.each do |vc| %>
            <li><%= "#{vc.volume} oz - #{number_to_currency(vc.cost)}" %></li>
          <% end %>
        </ul>
      </p>
      
      <% if allowed? %>
        <div class="btn-group btn-group-sm" role="group" >
          <%= link_to "Edit", edit_product_path(product), class: "btn btn-secondary", id: "edit_product" %>
          <%= link_to "Delete", product , method: :delete, class: "btn btn-secondary", id: "delete_product", data: { confirm: "Are You Sure?" } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1>

<%= render 'form' %>

app/views/products/index.html.erb
<div class="container-fluid">

  <% if @category.present? %>
    <div class="row">
      <div class="col-12 col-md-auto">
        <h2><%= @category.name %></h2>
      </div>
      <% if allowed? %>
      <div class="col">
        <%= link_to "New #{@category.name.singularize}", new_category_product_path(@category.id), class: "btn btn-secondary" %>
      </div>
      <% end %>
    </div>
  <% end %>

  <%= render partial: 'product_details', collection: @products, as: :product %>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="container-fluid">
  <%= render partial: 'product_details', locals: {product: @product}, as: :product %>
</div>