config/routes.rb
Rails.application.routes.draw do
  resources :users, :only => [:new, :create]
  resources :products
  resources :volume_costs, only: [:new, :create, :edit, :update]
  
  resources :oils do
    resources :benefits
  end

  resources :categories do 
    resources :products, only: [:new, :create, :index]
    resources :volume_costs
  end

  get '/products/volume_costs/new' => 'volume_costs#new'

  root 'static_pages#home'
  get '/contact' => 'static_pages#contact'

  get    '/signup' => 'users#new'
  post   '/users' => 'users#create'
  get    '/login' => 'sessions#new'
  post   '/sessions' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'
  

end

app/models/benefit.rb
class Benefit < ActiveRecord::Base
  # has_many :oil_benefits
  # has_many :oils, through: :oil_benefits
  belongs_to :oil

  # validates :description, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, :dependent => :destroy
  has_many :volume_costs

  validates :name, uniqueness: true
  validates :name, presence: true

  before_save :naming_convention

  def naming_convention
    self.name = self.name.titleize.pluralize
  end

end

app/models/oil.rb
class Oil < ActiveRecord::Base
  has_many :product_oils
  has_many :products, through: :product_oils

  # has_many :oil_benefits
  # has_many :benefits, through: :oil_benefits
  has_many :benefits

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/oil_benefit.rb
class OilBenefit < ActiveRecord::Base
  belongs_to :oil 
  belongs_to :benefit 
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  has_many :product_oils
  has_many :oils, through: :product_oils

  has_many :product_volume_costs
  has_many :volume_costs, through: :product_volume_costs

  validates :name, uniqueness: true
  validates :name, :description, :category_id, presence: true
  validates :oil_ids, :presence => {:message => "must select at least one Oil" }

  before_save :naming_convention

  scope :sort_alpha, -> { order(:name) }

  def volumes_with_data
    volume_costs.where('volume > ? AND cost > ?', 0, 0).order(:volume)
  end

  def naming_convention
    self.name = self.name.capitalize
  end

end

app/models/product_oil.rb
class ProductOil < ActiveRecord::Base
  belongs_to :product
  belongs_to :oil
end

app/models/product_volume_cost.rb
class ProductVolumeCost < ActiveRecord::Base
  belongs_to :product
  belongs_to :volume_cost
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, :email, presence: true
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: /\A\S+@.+\.\S+\z/,
    message: "must contain an @ and a ." }

  def self.find_or_create_by_omniauth(fb_auth_hash)
    where(email: fb_auth_hash["info"]["email"]).first_or_create do |user|
      user.name = fb_auth_hash["info"]["name"]
      user.password = SecureRandom.hex
    end
  end

end

app/models/volume_cost.rb
class VolumeCost < ActiveRecord::Base
  has_many :product_volume_costs
  has_many :products, through: :product_volume_costs
  belongs_to :category

  validates :volume, :cost, presence: true
  validates :volume, :cost, numericality: true

end

app/controllers/benefits_controller.rb
class BenefitsController < ApplicationController
  before_action :set_oil
  before_action :set_benefit, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show, :index]

  def new
    @benefit = Benefit.new
  end

  def create
    @benefit = @oil.benefits.build(benefit_params)

    if @benefit.save
      respond_to do |f|
        f.html { redirect_to oil_path(@oil) }
        f.json { render :json => @benefit }
      end
    else
      render "oils/show"
    end
  end

  def index
    @benefits = @oil.benefits
  end

  def show
  end

  def edit
  end

  def update
    if @benefit.update(benefit_params)
      redirect_to benefit_path(@benefit)
    else
      redirect_to edit_benefit_path(@benefit)
    end
  end

  def destroy
    @benefit.delete

    redirect_to benefits_path
  end

  private

  def benefit_params
    params.require(:benefit).permit(:description)
  end

  def set_benefit
    @benefit = Benefit.find(params[:id])
  end

  def set_oil
    @oil = Oil.find(params[:oil_id])
  end

end

app/controllers/oils_controller.rb
class OilsController < ApplicationController
  before_action :set_oil, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show, :index]

  def new
    @oil = Oil.new
  end

  def create
    @oil = Oil.new(oil_params)

    if @oil.save
      redirect_to oil_path(@oil)
    else
      render :new
    end
  end

  def show
    @oil_benefits = @oil.benefits
    @benefit = Benefit.new

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @oil }
    end
  end

  def edit
  end

  def update
    if @oil.update(oil_params)
      redirect_to oil_path(@oil)
    else
      redirect_to edit_oil_path(@oil)
    end
  end

  def index
    @oils = Oil.all

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @oils }
    end
  end

  def destroy
    @oil.destroy

    respond_to do |f|
      f.json { render :json => @oil }
      f.html { redirect_to oils_path }
    end
  end

  private

  def oil_params
    params.require(:oil).permit(:name, :description, :benefit_ids => [])
  end

  def set_oil
    @oil = Oil.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    return render :new unless @user.save
    session[:user_id] = @user.id
    redirect_to root_path, notice: "You have successfully signed up!"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/categories_helper.rb
module CategoriesHelper

end

app/helpers/navigation_helper.rb
module NavigationHelper

  def link_helper(link_title, path, class_name)
    link_to link_title, path, class: class_name
  end

  def all_categories
    @categories ||= Category.all
  end

  def product_category_index_dropdown
    content_tag(:div, :class => 'dropdown-menu') do 
      all_categories.collect do |category|
        classTitle = category.name.parameterize('_')

        content_tag(:a, category.name, {class: "product dropdown-item", href: "/categories/#{ category.id }/products", id: category.id})
      end.join.html_safe
    end
  end

  def nav_link_helper(name, path, method = :get)
    content_tag(:li, class: 'nav-item') do 
      link_to name, path, method: method, class: 'nav-link', id: name.underscore
    end
  end

  def nav_text_helper(user)
    content_tag(:li, "Hello, #{ user.name }", class: 'nav-link') do 
      "Hello, #{ user.name }"
    end
  end

  def authentication_items
    content_tag(:ul, class: "nav navbar-nav navbar-right col-md-auto") do 
      if current_user
        link1 = nav_text_helper(current_user)
        link2 = nav_link_helper("Log Out", logout_path, :delete)
      else
        link1 = nav_link_helper("Sign Up", new_user_path)
        link2 = nav_link_helper("Login", login_path)
      end
      (link1 + link2).html_safe
    end
  end

end

app/helpers/oils_helper.rb
module OilsHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def next_product_link(action, product_id)
    if action === "show"
      link_to "Next Product", "#", class: "next-product", data: { id: product_id, limit: product_count }
    end
  end

  def product_count
    return Product.all.size
  end


# <a href="#" class="next-product" data-id=params["id"]>Next Product</a>
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/volume_costs_helper.rb
module VolumeCostsHelper
end

app/views/layouts/_messages.html.erb
<%= content_tag(:div, flash[:notice], :class => "alert alert-success") if flash[:notice] %>
<%= content_tag(:div, flash[:error], :class => "alert alert-warning") if flash[:error] %>
<%= content_tag(:div, flash[:alert], :class => "alert alert-danger") if flash[:alert] %>

app/views/layouts/_navbar_admin_items.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Admin Items
  </a>
  <div class="dropdown-menu">
    <h6 class="dropdown-header">ADD NEW:</h6>
    <%= link_helper("Oil", new_oil_path, "dropdown-item") %>
    <%= link_helper("Category", new_category_path, "dropdown-item") %>
    <%= link_helper("Volume/Cost", new_volume_cost_path, "dropdown-item") %>
    <%= link_helper("Product", new_product_path, "dropdown-item") %>
    <div class="dropdown-divider"></div>
    <h6 class="dropdown-header">REMOVE:</h6>
    <%= link_helper("Oil", oils_path, "dropdown-item") %>
    <%= link_helper("Category", categories_path, "dropdown-item") %>
  </div>
</li>

app/views/layouts/_navigation_bar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Oils of Joy</a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <%= nav_link_helper("Oils", oils_path) %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Products
        </a>
        <%= product_category_index_dropdown %>
      </li>
      <li>
        <%= nav_link_helper("Contact Me", contact_path) %>
      </li>
      <% if current_user.try(:admin?) %>
        <%= render partial: 'layouts/navbar_admin_items' %>
      <% end %>
    </ul>
  </div>
  <%= authentication_items %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OilsOfJoy</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
  <script src="https://use.fontawesome.com/6af8f1a327.js"></script>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation_bar' %>

<div class="alert">
  <%= render 'layouts/messages' %>
</div>

<div class="container-fluid">
  <div class="app-container">
    <%= yield %> 
  </div>
</div>

</body>
</html>